version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - ${PLEX_PORT}:${PLEX_PORT}/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    hostname: locahost
    volumes:
      - ./config/plex/:/config
      - ./plex/transcode/temp:/transcode
      - ./plex/movies:/movies
      - ./plex/tvseries:/tv

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
    ports:
      - ${OVERSEERR_PORT}:${OVERSEERR_PORT}
    restart: unless-stopped
    volumes:
      - ./config/overseerr/:/config
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
    volumes:
      - ./config/radarr/:/config
      - ./plex/movies:/movies
      - ./medias/downloads:/downloads
      - ./medias/movies:/movies 
    ports:
      - ${RADARR_PORT}:${RADARR_PORT}
    restart: unless-stopped
    depends_on:
      - overseerr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ_PARIS}
    volumes:
      - ./config/sonarr/:/config
      - ./plex/tvseries:/tv
      - ./medias/downloads:/downloads
      - ./medias/tvseries:/tv 
    ports:
      - ${SONARR_PORT}:${SONARR_PORT}
    restart: unless-stopped
    depends_on:
      - overseerr
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_LONDON}
    volumes:
      - ./config/bazarr/:/config
      - ./medias/movies:/movies
      - ./medias/tvseries:/tv
    ports:
      - ${BAZARR_PORT}:${BAZARR_PORT}
    restart: unless-stopped
networks:
  default:
    name: my-plex-network