# version: "2.1"
# services:
#   plex:
#     image: plexinc/pms-docker:latest
#     container_name: plex
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - VERSION=docker
#       - PLEX_CLAIM= #optional
#     ports:  
#       - 32400:32400
#     volumes:
#       - ./plex/config:/config
#       - ./plex/medias/tvseries:/tv
#       - ./plex/medias/movies:/movies
#     restart: unless-stopped

version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=TZ=Europe/Paris
      - PLEX_CLAIM=claim-J4j_T1omNQqfngxGqnG8
      - ADVERTISE_IP=http://
    hostname: locahost
    volumes:
      - ./plex/plex/transcode/temp:/transcode
      - ./plex/plex/config:/config
      - ./plex/plex/medias/tvseries:/tv
      - ./plex/plex/medias/movies:/movies

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./plex/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./`/sonarr/config:/config
      - ./plex/sonarr/tvseries:/tv #optional
      - ./plex/sonarr/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - overseerr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./plex/radarr/config:/config
      - ./plex/radarr/movies:/movies #optional
      - ./plex/radarr/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - overseerr

