version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - ${PLEX_PORT}:${PLEX_PORT}/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TZ=Europe/Paris
      - PLEX_CLAIM=claim-J4j_T1omNQqfngxGqnG8
      - ADVERTISE_IP=http://
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    hostname: locahost
    volumes:
      - ./config/plex/:/config
      - ./plex/transcode/temp:/transcode
      - ./plex/movies:/movies
      - ./plex/tvseries:/tv

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
    ports:
      - 5055:5055
    restart: unless-stopped
    volumes:
      - ./config/overseerr/:/config
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
    volumes:
      - ./config/radarr/:/config
      - ./plex/movies:/movies
      - ./media/downloads:/downloads
      - ./media/movies:/movies 
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - overseerr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ_PARIS}
    volumes:
      - ./config/sonarr/:/config
      - ./plex/tvseries:/tv
      - ./media/downloads:/downloads
      - ./media/tvseries:/tv 
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - overseerr
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_LONDON}
    volumes:
      - ./config/bazarr/:/config
      - ./media/movies:/movies
      - ./media/tvseries:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
networks:
  default:
    name: my-plex-network
    external: true