version: '2'
services:

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
      - RUN_OPTS=run options here
    volumes:
      - ./config/jackett/config:/config
    ports:
      - ${JACKETT_PORT}:${JACKETT_PORT}
    restart: unless-stopped

  openvpn:
    image: ebrianne/docker-deluge-openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=nl-free-128.protonvpn.net.udp
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=${LOCAL_NETWORK}
    volumes:
      - ./config/openvpn:/etc/openvpn/custom
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - ${OPENVPN_PORT}:${OPENVPN_PORT}
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: "service:openvpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
      - UMASK_SET=022
    volumes:
      - ./config/deluge/:/config
      - ./medias/downloads:/downloads
      - ./medias/movies:/movies
      - ./medias/tvseries:/tv
    depends_on:
      - openvpn
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ_PARIS}
      - URL=mybase1.duckdns.org
      - ONLY_SUBDOMAINS=true
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
    volumes:
      - ./config/swag/:/config
    ports:
      - ${SWAG_PORT}:${SWAG_PORT}
      - ${NGINX_PORT}:${NGINX_PORT}
    restart: unless-stopped
networks:
  default:
    name: my-plex-network